-- Method-specific checks derived from the supplied procurement matrix.
-- Source versions conflict (14th amendment, 2082 vs 16th amendment, 2083);
-- verify every threshold/reference against the current official text before use.
INSERT INTO checklist_items (
    checklist_code, stage_id, stage_number, inspection_area, legal_reference,
    required_documents, inspection_question, possible_irregularity,
    default_risk_level, sort_order
) VALUES
('PROC-143', (SELECT id FROM checklist_stages WHERE stage_number = 26), 26,
 'विशेष विधि छनोट र कानूनी आधार', 'ऐन दफा ८; लागू विधिअनुसार सम्बन्धित नियम',
 'लागत अनुमान, बजार अध्ययन, विधि छनोट टिप्पणी, लागू नियमको प्रति र अधिकारप्राप्त अधिकारीको स्वीकृति',
 'विशेष/वैकल्पिक विधि छनोट गर्दा रकम, वस्तु/कामको प्रकृति र विधिमा प्रवेशका सबै कानूनी शर्त लिखित रूपमा परीक्षण गरी स्वीकृत गराइएको छ?',
 'सुविधा, ढिलाइ वा प्रतिस्पर्धा सीमित गर्ने उद्देश्यले आधार नपुगेको अपवाद विधि रोज्ने', 'अत्यन्त उच्च', 143),
('PROC-144', (SELECT id FROM checklist_stages WHERE stage_number = 26), 26,
 'सोझै खरिद सीमा र दर विश्लेषण', 'ऐन दफा ४१; नियम ८५(१)(क) (Matrix reference)',
 'आर्थिक वर्षगत खरिद विवरण, लागत अनुमान, बजार अध्ययन, लागू भए तीन लिखित दरभाउ, तुलना-पत्र र स्वीकृति',
 'सामान्य मालसामान/निर्माणको सोझै खरिद Matrix मा उल्लेखित सीमा र quotation शर्तभित्र छ, समग्र समान आवश्यकता जोडिएको छ र मूल्य औचित्य प्रमाणित छ?',
 'खरिद टुक्र्याई सीमा छल्ने, लागू सीमा नाघ्ने वा दरभाउ/मूल्य तुलना नदेखाउने', 'अत्यन्त उच्च', 144),
('PROC-145', (SELECT id FROM checklist_stages WHERE stage_number = 26), 26,
 'सोझै परामर्श तथा विशेष मर्मत सेवा', 'नियम ८५(१)(क१)–(क३) (Matrix reference)',
 'TOR/diagnosis, specialist वा अधिकृत service-centre प्रमाण, लागत अनुमान, विकल्प/दर विश्लेषण र विधि स्वीकृति',
 'परामर्श, गाडी/मेसिनरी वा IT मर्मतको विशेष direct route लागू हुँदा सम्बन्धित उपनियम, रकम सीमा, आवश्यकता र provider eligibility छुट्टाछुट्टै प्रमाणित गरिएको छ?',
 'सामान्य खरिदलाई विशेषज्ञ सेवा/मर्मत भनेर वर्गीकरण गरी प्रतिस्पर्धा छल्ने', 'उच्च', 145),
('PROC-146', (SELECT id FROM checklist_stages WHERE stage_number = 26), 26,
 'सिलबन्दी दरभाउ र पुनःआह्वान', 'ऐन दफा ४०; नियम ८४',
 'स्वीकृत estimate/RFQ, notice, प्राप्त दरभाउ, opening record, responsive comparison र पुनःआह्वान निर्णय',
 'दरभाउपत्रको रकम सीमा, वस्तु-विशेष अपवाद, म्याद, न्यूनतम प्रभावग्राही प्रस्ताव तथा प्रस्ताव नपुगेको अवस्थामा पुनःआह्वान/अन्य कदम लागू नियमबमोजिम जाँचिएको छ?',
 'अयोग्य दरभाउ स्वीकार्ने, आवश्यक पुनःआह्वान नगर्ने वा प्रकाशित मापदण्ड बदलेर छनोट गर्ने', 'उच्च', 146),
('PROC-147', (SELECT id FROM checklist_stages WHERE stage_number = 26), 26,
 'सीमित बोलपत्र', 'नियम ३१ग (Matrix reference)',
 'पात्र बजार-स्रोतको सर्वेक्षण, बढीमा तीन उपलब्ध पक्षको प्रमाण, विधि औचित्य, एक तह माथिको स्वीकृति र समान invitation',
 'बजारमा योग्य आपूर्तिकर्ता/निर्माण व्यवसायी/परामर्शदाता बढीमा तीन जना मात्र भएको प्रमाण र Matrix ले तोकेको माथिल्लो तहको स्वीकृति लिएर सबैलाई समान अवसर दिइएको छ?',
 'बजार सर्वेक्षणबिना सीमित सूची बनाउने वा आवश्यक पक्षलाई नबोलाउने', 'उच्च', 147),
('PROC-148', (SELECT id FROM checklist_stages WHERE stage_number = 26), 26,
 'क्याटलग सपिङ', 'नियम ३१ख (Matrix reference)',
 'वस्तु विधिमा योग्य भएको औचित्य, निर्माता/अधिकृत विक्रेता प्रमाण, प्रकाशित catalogue/price list, बजार मूल्य तुलना',
 'क्याटलग सपिङ लागू हुने वस्तु र अधिकृत विक्रेता प्रमाणित गरी specification, प्रकाशित मूल्य, warranty र total cost तुलना गरिएको छ?',
 'ब्रान्ड मनपरी निर्दिष्ट गर्ने, अनधिकृत विक्रेता/पुरानो मूल्य प्रयोग गर्ने वा विधि-योग्यता नदेखाउने', 'उच्च', 148),
('PROC-149', (SELECT id FROM checklist_stages WHERE stage_number = 26), 26,
 'ई-मार्केटप्लेस तथा रिभर्स अक्सन', 'नियम ३१ञ र ८६क(२) (Matrix reference)',
 'channel eligibility, estimate, समान specification, electronic invitations, platform audit log, मूल्याङ्कन र approval',
 'single-source/तीन quotation/reverse-auction channel मध्ये लागू विकल्प र रकम सीमा पुष्टि गरी प्रणालीको पूरा electronic audit trail राखिएको छ?',
 'गलत channel वा सीमा प्रयोग गर्ने, auction लग नजोगाउने वा सबै सहभागीलाई समान अवसर नदिने', 'उच्च', 149),
('PROC-150', (SELECT id FROM checklist_stages WHERE stage_number = 26), 26,
 'बाई-ब्याक मूल्याङ्कन', 'नियम ३१घ (Matrix reference)',
 'पुरानो सम्पत्तिको स्वतन्त्र अवस्था/मूल्याङ्कन, नयाँ वस्तुको specification, अलग buy-back credit र net-cost तुलना',
 'पुरानो वस्तुको मूल्याङ्कन र नयाँ वस्तुको मूल्य अलग देखाई पूर्वप्रकाशित आधारमा evaluated net cost तुलना गरिएको छ?',
 'trade-in credit वा पुरानो सम्पत्तिको मूल्यबाट नयाँ खरिदको वास्तविक लागत लुकाउने', 'उच्च', 150),
('PROC-151', (SELECT id FROM checklist_stages WHERE stage_number = 26), 26,
 'Proprietary/एकल स्रोत वस्तु', 'नियम ८५(३), (३क) (Matrix reference)',
 'patent/exclusive-right प्रमाण, विकल्प/बजार अध्ययन, compatibility औचित्य, price benchmark र कारणयुक्त approval',
 'proprietary वा single-source खरिद गर्दा अपवादको ठोस प्रमाण, विकल्पको परीक्षण, मूल्य उचितता र अधिकारप्राप्त अधिकारीको कारणयुक्त स्वीकृति छ?',
 'brand preference वा सामान्य compatibility दाबीलाई एकल स्रोतको आधार बनाउने', 'अत्यन्त उच्च', 151),
('PROC-152', (SELECT id FROM checklist_stages WHERE stage_number = 26), 26,
 'WHO pre-qualified औषधि खरिद', 'नियम ८५(१ख१) (Matrix reference; आधिकारिक पाठबाट पुष्टि)',
 'औषधि आवश्यकता, नियामक दर्ता, WHO prequalification, sole-producer प्रमाण, बजार benchmark र negotiation minutes',
 'विशेष औषधि route लागू गर्दा WHO prequalification, नियामक स्वीकृति, एकमात्र योग्य उत्पादक र मूल्य-उचितता स्वतन्त्र रूपमा प्रमाणित गरिएको छ?',
 'prequalification वा एकल उत्पादकको अवस्था अप्रमाणित हुँदा सोझै वार्ता गर्ने', 'अत्यन्त उच्च', 152),
('PROC-153', (SELECT id FROM checklist_stages WHERE stage_number = 26), 26,
 'स्वदेशी घरेलु/औषधिजन्य उत्पादन अपवाद', 'नियम ८५(१क), (१घ) (Matrix reference)',
 'नेपाल राजपत्रको सूचीसँग मिलान, उद्योग/उत्पादन दर्ता, प्रकाशित मूल्य, गुणस्तर प्रमाण र सीमा गणना',
 'घरेलु उद्योग वा नेपाल-उत्पादित औषधिको विशेष सीमा प्रयोग गर्दा वस्तु र उत्पादक लागू राजपत्र/नियमको परिभाषाभित्र पर्छन्?',
 'सामान्य घरेलु आपूर्तिकर्ता वा अयोग्य उत्पादनलाई विशेष खरिद छुटमा राख्ने', 'उच्च', 153),
('PROC-154', (SELECT id FROM checklist_stages WHERE stage_number = 26), 26,
 'स्वदेशी प्राथमिकता/JV शर्त', 'नियम ३१ङ–३१च (Matrix reference)',
 'NCB/ICB को निर्णय, प्रकाशित preference formula, origin/JV documents, सीमा विश्लेषण र calculation sheet',
 'स्वदेशी-मात्र प्रतिस्पर्धा वा domestic preference लागू गर्दा सीमा, JV/उत्पत्ति शर्त र गणना बोलपत्र कागजातमा पहिले नै खुलाइएको छ?',
 'मूल्याङ्कनपछि preference formula थप्ने वा योग्य विदेशी/स्वदेशी पक्षलाई असमान व्यवहार गर्ने', 'उच्च', 154),
('PROC-155', (SELECT id FROM checklist_stages WHERE stage_number = 26), 26,
 'उपभोक्ता समिति/लाभग्राही समुदाय योग्यता', 'ऐन दफा ४४; नियम ९७',
 'खुला आमभेला minutes, लाभग्राही सूची, committee गठन/दर्ता, कार्यको श्रममूलक औचित्य र स्वीकृत लागत',
 'समिति विधि प्रयोग भएको अवस्थामा प्रत्यक्ष लाभग्राही सहभागिता, समिति गठन र नियम ९७ को कार्य-योग्यता प्रमाणित गरिएको छ?',
 'कृत्रिम समिति बनाई contractor procurement वा प्रतिस्पर्धा सीमा छल्ने', 'अत्यन्त उच्च', 155),
('PROC-156', (SELECT id FROM checklist_stages WHERE stage_number = 26), 26,
 'उपभोक्ता समिति लागत/कार्यान्वयन नियन्त्रण', 'नियम ९७ (Matrix reference)',
 'लागत साझेदारी/योगदान गणना, सम्झौता, site measurement, गुणस्तर परीक्षण, किस्ता भुक्तानी र सार्वजनिक परीक्षण',
 'योगदान लागू हुने सीमा, सम्झौता, नापजाँच, भुक्तानी, कामको गुणस्तर र सार्वजनिक परीक्षणको प्रमाण पूरा छ?',
 'योगदान/खर्च अभिलेख नगर्ने, कामभन्दा बढी भुक्तानी गर्ने वा लागू निषेध छल्ने', 'उच्च', 156),
('PROC-157', (SELECT id FROM checklist_stages WHERE stage_number = 26), 26,
 'राशन दर/लागत अनुमान समिति', 'नियम ८८–९३; समिति नियम ८८(२) (Matrix reference)',
 'beneficiary/अवधि/scale, समिति गठन, बजार सर्वेक्षण, transport/storage सहित estimate र स्वीकृति',
 'राशन खरिदमा परिमाण/स्तर र नियम ८८ अनुसार समिति गठन गरी बजार/ढुवानी/भण्डारण लागतसहित अनुमान तयार गरिएको छ?',
 'पुरानो/हचुवा दर वा लाभग्राही संख्या प्रयोग गरी लागत/परिमाण बढाउने', 'उच्च', 157),
('PROC-158', (SELECT id FROM checklist_stages WHERE stage_number = 26), 26,
 'राशन आपूर्ति/गुणस्तर मिलान', 'नियम ८८–९३',
 'बोलपत्र/करार, lot-wise delivery, तौल/गुणस्तर/expiry जाँच, stock र वितरण register, invoice',
 'हरेक राशन आपूर्तिमा quantity, वजन, गुणस्तर/म्याद, भण्डार दाखिला र वास्तविक वितरण मिलान गरी भुक्तानी गरिएको छ?',
 'नपुगेको, बिग्रेको वा नदिइएको राशनको भुक्तानी गर्ने', 'अत्यन्त उच्च', 158),
('PROC-159', (SELECT id FROM checklist_stages WHERE stage_number = 26), 26,
 'घर/जग्गा भाडा मूल्याङ्कन', 'नियम ९४',
 'स्थान/आवश्यकता टिप्पणी, house-rent committee inspection/valuation, comparable rent, budget र owner documents',
 'भाडा अघि आवश्यक स्थान/क्षेत्रफल, विकल्प, बजार तुलना र नियम ९४ को मूल्याङ्कन समितिको प्रतिवेदन लिइएको छ?',
 'मूल्याङ्कन/प्रतिस्पर्धाबिना महँगो वा अनुपयुक्त सम्पत्ति भाडामा लिने', 'उच्च', 159),
('PROC-160', (SELECT id FROM checklist_stages WHERE stage_number = 26), 26,
 'भाडा रकम र वार्ता सीमा', 'नियम ९४ (Matrix reference)',
 'स्थानअनुसार वार्षिक दायित्व, लागू threshold verification, notice/वार्ता record र सक्षम अधिकारीको approval',
 'काठमाडौं/बाहिरको फरक सीमा, notice अवधि वा direct negotiation प्रयोग गर्दा हालको नियमसँग रकम र स्वीकृति मिलाइएको छ?',
 'स्थान नखुलाई गलत direct threshold प्रयोग गर्ने वा lease दायित्व टुक्र्याउने', 'उच्च', 160),
('PROC-161', (SELECT id FROM checklist_stages WHERE stage_number = 26), 26,
 'दैनिक सेवा करार threshold/SLA', 'नियम ९५ (Matrix reference)',
 'वार्षिकीकृत staffing/wage estimate, TOR/SLA, प्रतिस्पर्धात्मक notice वा वार्ता, labour/tax compliance',
 'सुरक्षा/सरसफाइ/अन्य दैनिक सेवा करारको जम्मा अवधिको अनुमान, रकम सीमा, प्रतिस्पर्धा/वार्ता र सेवा स्तरको शर्त नियम ९५ अनुसार छ?',
 'वार्षिक मूल्य नजोड्ने, सेवा करार टुक्र्याउने वा श्रम/कर दायित्व बेवास्ता गर्ने', 'उच्च', 161),
('PROC-162', (SELECT id FROM checklist_stages WHERE stage_number = 26), 26,
 'Design-Build/EPC सम्भाव्यता र output', 'नियम ३ तथा २२(२), २२(३) (Matrix reference)',
 'economic/social/technical/environment feasibility, conceptual design, site data, output specification र risk matrix',
 'EPC/Design-Build प्रयोग हुँदा feasibility, conceptual design, performance requirement, site/interface र risk allocation स्वीकृत छन्?',
 'अपर्याप्त design/feasibility का कारण scope, लागत वा जिम्मेवारी अस्पष्ट राख्ने', 'अत्यन्त उच्च', 162),
('PROC-163', (SELECT id FROM checklist_stages WHERE stage_number = 26), 26,
 'EPC मूल्याङ्कन/सम्झौता नियन्त्रण', 'नियम २२(२), २२(३); लागू SBD/सम्झौता',
 'approved procurement strategy, evaluation method, performance/security tests, commissioning, defects, variation र handover records',
 'Design-Build/EPC प्रस्ताव पूर्वनिर्धारित technical/output criteria मा मूल्याङ्कन गरी performance test, defect duty र change-control सम्झौतामा राखिएको छ?',
 'अनिश्चित output, evaluation वा दोष दायित्वमा EPC award/भुक्तानी गर्ने', 'अत्यन्त उच्च', 163),
('PROC-164', (SELECT id FROM checklist_stages WHERE stage_number = 26), 26,
 'Framework ceiling/duration/call-off', 'नियम २१क (Matrix reference)',
 'aggregated demand, ceiling estimate, अवधि, master agreement, competition/allocation rules र cumulative call-off log',
 'Framework agreement मा अवधि, कुल रकम/परिमाणको ceiling, call-off विधि र प्रत्येक call-off को स्वीकृति स्पष्ट छ?',
 'framework लाई अवधि/सीमाबिनाको खुला खरिद अधिकारझैँ प्रयोग गर्ने', 'अत्यन्त उच्च', 164),
('PROC-165', (SELECT id FROM checklist_stages WHERE stage_number = 26), 26,
 'Design प्रतियोगिता', 'नियम ८७',
 'design brief/TOR, jury appointment, anonymous submission log, rubric, IP terms, score sheets and approval',
 'वास्तुकला/शहरी डिजाइन प्रतियोगितामा jury, conflict declaration, anonymity, पूर्वप्रकाशित मूल्याङ्कन आधार र बौद्धिक सम्पत्ति व्यवस्था छन्?',
 'नियम/criteria सार्वजनिक नगरी पक्षपातपूर्ण design चयन गर्ने वा पछिल्लो contract स्वतः दिने', 'उच्च', 165),
('PROC-166', (SELECT id FROM checklist_stages WHERE stage_number = 26), 26,
 'पुनःबोलपत्र/पुनःआह्वान निर्णय', 'ऐन दफा २६; लागू बोलपत्र/दरभाउ नियम',
 'मूल opening/evaluation report, cancellation/rejection reasons, bidder notice, revised document approval and new publication',
 'कुनै पनि सारभूत रूपमा प्रभावग्राही proposal नआएको वा कानूनी कारणमा खरिद रद्द गर्दा कारणयुक्त निर्णय, सबैलाई सूचना र नयाँ आह्वानको समान मापदण्ड कायम छन्?',
 'कारण नखुलाई रद्द गर्ने, criteria आफूअनुकूल बदल्ने वा अनुचित रूपमा दोहोर्‍याउने', 'उच्च', 166),
('PROC-167', (SELECT id FROM checklist_stages WHERE stage_number = 26), 26,
 'विशेष परिस्थिति खरिद', 'ऐन दफा ६६',
 'आपतकाल/हानि प्रमाण, तुरुन्त खरिद औचित्य, सीमित scope/price evidence, approval र एक तह माथि जानकारी',
 'विशेष परिस्थिति अपवाद प्रयोग गर्दा तत्कालीन खतरा, आवश्यक न्यूनतम scope, मूल्य औचित्य र माथिल्लो अधिकारीलाई विवरण दिने प्रक्रिया पूरा छ?',
 'सामान्य/पहिलेदेखि योजनाबद्ध कामलाई emergency भनेर प्रतिस्पर्धा छल्ने', 'अत्यन्त उच्च', 167),
('PROC-168', (SELECT id FROM checklist_stages WHERE stage_number = 27), 27,
 'परामर्श छनोट विधि/अधिकार', 'ऐन दफा ३०–३५; नियम ७०–८३',
 'TOR, complexity/selection rationale, estimated fee, approval and applicable EOI/RFP method',
 'परामर्श सेवा छनोटमा QCBS/QBS/FBS/LCS/roster/direct/single-source मध्ये कामको प्रकृतिअनुसार कारणयुक्त विधि र सक्षम अधिकारीको स्वीकृति छ?',
 'सबै consultancy मा एउटै विधि/ratio लगाउने वा अपवादको स्वीकृति नलिने', 'उच्च', 168),
('PROC-169', (SELECT id FROM checklist_stages WHERE stage_number = 27), 27,
 'परामर्श TOR/लागत अनुमान', 'नियम ३८ र लागू नियम ७०–८३',
 'need statement, TOR/deliverables, person-month/expenses, estimate, budget, intellectual-property/conflict requirements',
 'परामर्शको आवश्यकता, TOR, प्रतिफल, समय, जनशक्ति, खर्चको आधार र अनुमान स्वीकृत गरी प्रस्ताव आह्वानपूर्व राखिएको छ?',
 'अस्पष्ट TOR/अनुमानबाट scope change, अपारदर्शी मूल्याङ्कन वा अनावश्यक सेवा सिर्जना गर्ने', 'उच्च', 169),
('PROC-170', (SELECT id FROM checklist_stages WHERE stage_number = 27), 27,
 'EOI सीमा/राष्ट्रिय-अन्तर्राष्ट्रिय scope', 'ऐन दफा ३०; नियम ७० (Matrix reference)',
 'approved estimate, EOI threshold calculation, notice language/publication, shortlist criteria and responses',
 'Matrix मा दिइएका २०/५० लाख तथा १५ करोडका EOI/competition bands लागू नियमबाट पुष्टि गरी उपयुक्त सार्वजनिक वा छोटो EOI प्रक्रिया अपनाइएको छ?',
 'गलत EOI threshold/म्यादबाट योग्य consultant को प्रतिस्पर्धा सीमित गर्ने', 'उच्च', 170),
('PROC-171', (SELECT id FROM checklist_stages WHERE stage_number = 27), 27,
 'Roster र consultant shortlist', 'नियम ७२; नियम ७०',
 'अद्यावधिक roster, EOI notice/responses, published shortlist criteria, score sheets and RFP dispatch log',
 'मौजुदा सूची प्रयोग गर्दा दर्ता/अद्यावधिक र सबै eligible consultant लाई समान अवसर छ; खुला EOI आवश्यक हुँदा roster ले त्यसलाई प्रतिस्थापन गरेको छैन?',
 'टेलर-मेड shortlist, अपूर्ण roster वा eligible consultant लाई बिना कारण हटाउने', 'उच्च', 171),
('PROC-172', (SELECT id FROM checklist_stages WHERE stage_number = 27), 27,
 'RFP scoring र प्राविधिक प्रस्ताव क्रम', 'ऐन दफा ३३–३५; नियम ७१, ७४, ८१ (लागू हुनेअनुसार)',
 'approved RFP, technical criteria/weights/cutoff, signed individual and consolidated score sheets, dated technical report',
 'technical criterion, weight, cutoff र pass/fail आधार proposal प्राप्त हुनुअघि प्रकाशित गरी वित्तीय प्रस्ताव खोल्नुअघि technical मूल्याङ्कन बन्द/स्वीकृत गरिएको छ?',
 'proposal खोलेपछि score/weight/cutoff बदल्ने वा technical report भन्दा पहिले financial खोल्ने', 'अत्यन्त उच्च', 172),
('PROC-173', (SELECT id FROM checklist_stages WHERE stage_number = 27), 27,
 'QCBS संयुक्त मूल्याङ्कन', 'ऐन दफा ३५; नियम ७१(४)(क), ८१(१) (Matrix reference)',
 'RFP मा प्रकाशित technical/financial weights, normalization formula, score calculation, tie-break and combined report',
 'QCBS मा RFP मा पहिले नै तोकिएको technical/financial weighting र formula मात्र प्रयोग गरी score गणना पुनःजाँचिएको छ?',
 'सबै काममा ८०:२०/९०:१० blanket लागू गर्ने वा combined score गलत गणना गर्ने', 'अत्यन्त उच्च', 173),
('PROC-174', (SELECT id FROM checklist_stages WHERE stage_number = 27), 27,
 'QBS गुणवत्ता-आधारित छनोट', 'ऐन दफा ३५; नियम ७४(१)(ख), ७४(२) (Matrix reference)',
 'complexity/skill justification, required prior approval, TOR/RFP, technical ranking and negotiation record',
 'QBS छान्दा उच्च विशेषज्ञता/जटिलताको औचित्य र आवश्यक पूर्वस्वीकृति छ; उच्च-ranked proposal पछि मात्र financial वार्ता गरिएको छ?',
 'आधार/स्वीकृतिबिना QBS प्रयोग गर्ने वा ranking छलेर वार्ता गर्ने', 'उच्च', 174),
('PROC-175', (SELECT id FROM checklist_stages WHERE stage_number = 27), 27,
 'FBS निश्चित बजेट छनोट', 'ऐन दफा ३५(१)(ग); नियम ७१(४)(ख), ८१(३) (Matrix reference)',
 'पूर्वस्वीकृत fixed budget, affordability analysis, RFP disclosure, technical report and budget-compliance comparison',
 'FBS मा कुल budget proposal खोल्नुअघि निश्चित/प्रकाशित छ, budget भन्दा माथिका proposal नियमअनुसार छुट्याइएका छन् र budget भित्रको highest technical score सिफारिस गरिएको छ?',
 'proposal हेरेपछि budget ceiling बदल्ने वा budget भन्दा बढी प्रस्ताव स्वीकार गर्ने', 'उच्च', 175),
('PROC-176', (SELECT id FROM checklist_stages WHERE stage_number = 27), 27,
 'LCS न्यूनतम लागत छनोट', 'ऐन दफा ३५(१)(घ); नियम ७४(३), ८१(४) (Matrix reference)',
 'standard/simple TOR rationale, RFP मा प्रकाशित minimum technical threshold, technical-first report and evaluated price table',
 'LCS प्रयोग गर्न काम सरल/standard भएको प्रमाण छ र technical threshold पार गर्ने consultant मध्ये मात्र न्यूनतम evaluated cost छानिएको छ?',
 'जटिल काममा LCS प्रयोग गर्ने वा technical pass नगरेको न्यून मूल्य प्रस्ताव छान्ने', 'उच्च', 176),
('PROC-177', (SELECT id FROM checklist_stages WHERE stage_number = 27), 27,
 'वार्ता/सीमित परामर्श खरिद', 'नियम ८२ (Matrix reference)',
 'सेवाको सूचीमा पर्ने प्रमाण, रकम सीमा, तीन प्रस्ताव (लागू भए), तुलनात्मक मूल्याङ्कन र माथिल्लो तहको approval',
 'तालिम/गोष्ठी/सेमिनारमा negotiated route प्रयोग गर्दा सेवा र रकम नियम ८२ भित्र छन् तथा Matrix ले भनेको तीन प्रस्ताव/स्वीकृति लागू पाठबाट मिलाइएको छ?',
 'सामान्य consultancy लाई negotiation exception भनेर प्रतिस्पर्धा हटाउने', 'उच्च', 177),
('PROC-178', (SELECT id FROM checklist_stages WHERE stage_number = 27), 27,
 'Single-source consultant', 'नियम ८३ (Matrix reference)',
 'कानूनी exception ground, market/alternative search, unique expertise/continuity proof, estimate, COI check and approval',
 'एकल स्रोत परामर्शदाताको नियमगत अपवाद, विकल्प नभएको प्रमाण, मूल्य benchmark र लिखित स्वीकृति अभिलेख गरिएको छ?',
 'incumbent consultant वा कम समय मात्रलाई sole-source को पर्याप्त कारण बनाउने', 'अत्यन्त उच्च', 178),
('PROC-179', (SELECT id FROM checklist_stages WHERE stage_number = 27), 27,
 'परामर्शदाता पेशागत दायित्व बीमा', 'नियम ८१(७) (Matrix reference; लागू पाठ पुष्टि)',
 'contract insurance clause, professional liability policy, insurer verification and submission date',
 'सम्झौतामा पेशागत दायित्व बीमा आवश्यक भए लागू अवधि/सीमाभित्र वैध policy प्राप्त गरी verify गरिएको छ?',
 'जोखिम कभर नगरी परामर्श कार्य गराउने वा अप्रमाणित policy स्वीकार गर्ने', 'मध्यम', 179),
('PROC-180', (SELECT id FROM checklist_stages WHERE stage_number = 27), 27,
 'परामर्श award authority र report', 'नियम ८१क; लागू financial delegation',
 'evaluation report, proposal approval band, delegation order, negotiation record, LoI/award and contract publication',
 'मूल्याङ्कन प्रतिवेदनपछि परामर्श प्रस्ताव नियम ८१क/निकायको delegation बमोजिम अधिकारीबाट स्वीकृत भई लागू सूचना/review र सम्झौता प्रक्रिया पूरा छ?',
 'अधिकार नपुगेको पदबाट प्रस्ताव स्वीकृत गर्ने वा मूल्याङ्कन/award record लुकाउने', 'अत्यन्त उच्च', 180)
ON CONFLICT (checklist_code) DO UPDATE SET
    stage_id = EXCLUDED.stage_id,
    stage_number = EXCLUDED.stage_number,
    inspection_area = EXCLUDED.inspection_area,
    legal_reference = EXCLUDED.legal_reference,
    required_documents = EXCLUDED.required_documents,
    inspection_question = EXCLUDED.inspection_question,
    possible_irregularity = EXCLUDED.possible_irregularity,
    default_risk_level = EXCLUDED.default_risk_level,
    sort_order = EXCLUDED.sort_order,
    is_active = TRUE,
    updated_at = CURRENT_TIMESTAMP;